# docker-compose.yml
version: "2.4"

volumes:
  db_data:

services:
  mysql:
    build:
      context: ./db/
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  boilerplate:
    container_name: boilerplate
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        - NPM_TOKEN=$NPM_TOKEN
    ports:
      - 8080:8080
    environment:
      - ENVIRONMENT=yap-local
      - MICROSERVICE_NAME=BOILERPLATE
      - MICROSERVICE_IP=0.0.0.0
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - SWAGGER_PORT=8080
      - MYSQL_HOST=mysql
      - MYSQL_USERNAME=user
      - MYSQL_PASSWORD=secret
      - MYSQL_DB_NAME=notes
    volumes:
      - .:/app:delegated
